name: Expo CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행
  pull_request:
    branches:
      - main  # main 브랜치에 PR 생성 시 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 버전 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: 'yarn'

      # 3. Yarn 설치
      - name: Install dependencies
        run: yarn install

      # 4. Expo 전역 설치
      - name: Install Expo globally
        run: yarn global add expo

      # 5. Lint 테스트
      - name: Run Lint
        run: yarn lint

      # 6. Expo 빌드 (Development/Production)
      - name: Expo Build (Development)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          yarn expo login --token $EXPO_TOKEN
          yarn expo start

